name: Notion Auto Link

on:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 4 * * *'
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # 强制 Node.js 24
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      DB_A: ${{ secrets.DB_A }}
      DB_B: ${{ secrets.DB_B }}

    steps:
      # 拉取仓库代码
      - uses: actions/checkout@v5  # 升级到最新版本，支持 Node.js 24

      # 安装 Python
      - uses: actions/setup-python@v6  # 升级到最新版本
        with:
          python-version: '3.10'

      # 安装依赖
      - run: pip install --upgrade pip
      - run: pip install requests

      # 运行你的脚本
      - run: python main.py
